behaviors:
  FlappyAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3

    # Configuration of the neural network
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 50000
    time_horizon: 200
    summary_freq: 2000
    keep_checkpoints: 5
    checkpoint_interval: 10000

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
      # GAIL
      gail:
        demo_path: Demos/Leve2FlappyAgentDemo.demo
        strength: 0.1

    # behavior cloning
    behavioral_cloning:
      demo_path: Demos/Leve2FlappyAgentDemo.demo
      strength: 0.1
